name: borneo_security_example
description: "Demonstrates how to use the borneo_security plugin."
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  borneo_security: 
    path: ../ 
  cupertino_icons: ^1.0.8
  ndialog: ^4.4.1+1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 